title: BridgeFEM.jl
description: Julia library for finite element analysis of bridges with temperature-dependent materials
theme: jekyll-theme-cayman
markdown: kramdown
highlighter: rouge

# Enable GitHub Pages features
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-toc

# Navigation menu
navigation:
  - title: Home
    url: /
  - title: Getting Started
    url: /getting-started
  - title: Theory
    url: /theory
  - title: API Reference
    url: /api-reference
  - title: Examples
    url: /examples

repository: yourusername/BridgeFEM.jl

# Enhanced math rendering with MathJax v3
kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
    preview_as_code: false
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Table of contents settings
toc:
  min_level: 1
  max_level: 4
  ordered_list: false
  no_toc_section_class: no_toc_section
  list_id: toc
  list_class: section-nav
  sublist_class: ""
  item_class: toc-entry
  item_prefix: toc-

# Custom CSS and JS
sass:
  style: compressed

# Collections for better organization
collections:
  examples:
    output: true
    permalink: /:collection/:name/
